services:
  bot:
    build: .
    env_file:
      - .env
    restart: unless-stopped

  odin:
    build: ./apps/odin
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - ODIN_PORT=9999
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - odysseus-network
    volumes:
      - odin_logs:/app/logs

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - odysseus-network
    volumes:
      - redis_data:/data

networks:
  odysseus-network:
    driver: bridge

volumes:
  odin_logs:
  redis_data:
